### ISSUE TITLE
Linker issue when building kernel: cannot find libbfd.so

### ISSUE THREAD

**Issue by torvic9** [ClangBuiltLinux/tc-build#104]
Hi,

When building the toolchain with the unmodified build-llvm.py script, and when using that toolchain to build the kernel, I get an error message as mentioned in the title (I don't have the exact message right here, but can post later).
I'm on Manjaro which is based on Arch.

So I modified the script in two points to fix the issue, however I don't yet know which one of those two was responsible. 
I guess it's the first one but I might be wrong:

1. Changed line 618
`        'LLVM_BINUTILS_INCDIR': dirs.root_folder.joinpath(utils.current_binutils(), "include").as_posix(),`
to
`        'LLVM_BINUTILS_INCDIR': dirs.root_folder.joinpath("usr", "include").as_posix(),`

My understanding is that with this change, it uses the system binutils.

2. Enabled dylib linking:
       `'LLVM_LINK_LLVM_DYLIB': 'ON',`
	`'CLANG_LINK_CLANG_DYLIB': 'ON',`

This is what Arch has in its build script.

**Comment by torvic9** [comment]
Exact error message:
```
/opt/clang11/bin/ld: error while loading shared libraries: libbfd-2.34.so: cannot open shared object file: No such file or directory
clang-11: error: unable to execute command: No such file or directory
clang-11: error: linker command failed due to signal (use -v to see invocation)
```

`$ /opt/clang11/bin/clang -v`
`clang version 11.0.0 (https://github.com/llvm/llvm-project 8a2bc9431193026454745d538cf7e5a5a6b6d5be)`
(N.B.: happens with any clang version)

**Comment by dileks** [comment]
How do you invoke `build-llvm.py`? You pass any options to it?

**Comment by torvic9** [comment]
Yes:

```
  -B ~/Clang \
  -p "clang;compiler-rt;lld" \
  --check-targets clang lld \
  --clang-vendor clang-vd \
  --lto thin \
  --pgo \
  -t X86 \
  -m ${_arch} \
  -b release/11.x
```

**Comment by dileks** [comment]
??? `-m ${_arch} \` ???

**Comment by torvic9** [comment]
It's part of a bash script.
`_arch=<architecture>` where architecture is either skylake or znver2 (my two platforms).

**Comment by dileks** [comment]
Hmm, I remember that using `-march` or was it `-mtune` did not give that speedup boost as expected.
Modern compilers are clever enough to chose the correct CPU/arch automatically.

Sorry, I have no experiences with adding `compiler-rt` as a project.

I tag my own style in local `llvm-project.git` thus I use `--no-update` and build `stage1-only`:
```
./build-llvm.py --no-update --build-type Release -p clang;lld -t X86 --clang-vendor '' --check-targets clang lld --build-stage1-only -B /home/dileks/src/llvm-toolchain/build --install-stage1-only -I /home/dileks/src/llvm-toolchain/install
```
`PGO` and/or `Thin-LTO` AFAICS to `multi-stage` builds.

One thing I can imagine is your `PATH` settings and search-path-order.
You followed the recommendations at the end when `tc-build` has finished?

Unsure, if there are Manjaro (ArchLinux) specific settings or some individual settings in your system causing this.

**Comment by torvic9** [comment]
Well for local builds one can also simply use `-march=native`.

I think that the paths are all fine. With the changes I mentioned above, everything works as expected.

Mind, in both cases, the toolchain builds just fine. 
It's only when I actually use the toolchain where the error pops up.

I guess that indeed this has to do with Arch/Manjaro and its binutils:
It seems that it is looking for `libbfd-2.34.so`, however on Arch, the file is called `libbfd-2.34.0.so`.
Maybe it's possible to simply create a symlink?

**Comment by dileks** [comment]
@nathanchance should help when it has to do with ArchLinux.

**Comment by torvic9** [comment]
> One thing I can imagine is your `PATH` settings and search-path-order.
> You followed the recommendations at the end when `tc-build` has finished?

Okay, I re-read it. But I don't quite understand.
It says "only one PATH modification is needed", but I'm not sure where to change that path?
I did build binutils as well, using the provided python script, they end up in the same "install" directory as the toolchain.

So do I need to add that directory to my PATH, e.g. `PATH=/path/to/binutils:$PATH` ?

Would be great if someone could comment on the changes I mentioned in OP, because quite frankly I'm not sure what I did there - except that it somehow works...

**Comment by dileks** [comment]
Why don't you tell the full story?

If you used `build-binutils.py` then you should adapt your PATH variable if you want to use the generated binaries:
```
PATH="/path/to/binutils/bin:/path/to/llvm-toolchain/bin:$PATH"
```

But we are talking about libs not found - check with `find` where your `libbfd-2.34.0.so` was installed.
See `man ldconfig`.

BTW, why do you want to build a `binutils` your own?

**Comment by torvic9** [comment]
> - check with `find` where your `libbfd-2.34.0.so` was installed.

On Arch, this is done with `pacman -Fyl binutils`. It's part of Arch's binutils.

> BTW, why do you want to build a `binutils` your own?

I do not. Just tested it with, and without. No change. What does change is the change I mentioned in point 1).

**Comment by dileks** [comment]
@torvic9 Please read this carefully.

https://github.com/ClangBuiltLinux/tc-build/blob/master/README.md#build-binutilspy

**Comment by torvic9** [comment]
I confirm that with change 1) the kernel builds correctly as expected.
Setting PATH does not help unless I'm too stupid to set it (which is entirely possible).

**Comment by dileks** [comment]
AFAICS for Arch Linux it is recommended to have all binaries in the same `install-folder` see `-I INSTALL_FOLDER, --install-folder INSTALL_FOLDER` option usable for both: `./build-binutils.py` and `./build-llvm.py`.

**Comment by torvic9** [comment]
> AFAICS for Arch Linux it is recommended to have all binaries in the same `install-folder` see `-I INSTALL_FOLDER, --install-folder INSTALL_FOLDER` option usable for both: `./build-binutils.py` and `./build-llvm.py`.

If I'm not mistaken, it's going automatically to `install/`. I didn't change that setting. Only the actual build directory.

**Comment by dileks** [comment]
Ah OK.

Some `ldconfig` tricks for a (selfmade) `/opt/llvm-toolchain` installation:
```
[ /etc/ld.so.conf.d/a-local-llvm.conf ]

# LLVM/Clang/LLD lib configuration
/opt/llvm-toolchain/lib
```

Feel free to adapt and test.

**Comment by nathanchance** [comment]
I won't be able to look into this until next week. However, `LLVM_BINUTILS_INCDIR` should just be used to build `LLVMgold.so`, not any dynamic linking.

**Comment by dileks** [comment]
Thanks @nathanchance for taking care.

**Comment by nathanchance** [comment]
@torvic9 wow I am so sorry that I lost track of this. Is this still relevant for you before I start investigating?

**Comment by torvic9** [comment]
@nathanchance, don't worry, I completely forgot about it too.
No, I don't think it's still relevant, this can be closed IMO.

But I do have a little suggestion, maybe add a `--dylib` parameter to the script, for example: https://github.com/torvic9/tc-build/commit/9ef530f4c24ef36148e8602d23112afffea7d525

**Comment by nathanchance** [comment]
Sure, I can try to take a look at that. Thanks for the follow up!
