### ISSUE TITLE
Building with PGO and ThinLTO support

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#109]
Impressed by the `PGO` related talks at `LPC 2020` I wanted to try it in combination with `ThinLTO`.

[ My first question ]
Why is it possible to set `stage1-only` tc-build options when I do a PGO + ThinLTO build which is AFAICS a `multi-stage` build?

[ My second question ]
How can I verify that especially `PGO` (and ThinLTO) was enabled?

My `build-llvm.py` line looks like this:
```
python3 ./build-llvm.py --no-update --build-type Release -p clang;lld -t X86 --clang-vendor '' -B /home/dileks/src/llvm-toolchain/build -I /home/dileks/src/llvm-toolchain/install --pgo --lto thin --check-targets clang lld
```

Tried to verify like this:
```
$ cd build/stage1

$ grep -i pgo CMakeCache.txt | grep ^[A-Z]
LLVM_ENABLE_IR_PGO:BOOL=OFF
LLVM_ENABLE_IR_PGO-ADVANCED:INTERNAL=1

$ grep -i lto CMakeCache.txt | grep ^[A-Z]
BENCHMARK_ENABLE_LTO:BOOL=OFF
CMAKE_DLLTOOL:FILEPATH=/usr/lib/llvm-11/bin/llvm-dlltool
LLVMDlltoolDriver_LIB_DEPENDS:STATIC=general;LLVMObject;general;LLVMOption;general;LLVMSupport;
LLVMLTO_LIB_DEPENDS:STATIC=general;LLVMAggressiveInstCombine;general;LLVMAnalysis;general;LLVMBinaryFormat;general;LLVMBitReader;general;LLVMBitWriter;general;LLVMCodeGen;general;LLVMCore;general;LLVMExtensions;general;LLVMInstCombine;general;LLVMLinker;general;LLVMMC;general;LLVMObjCARCOpts;general;LLVMObject;general;LLVMPasses;general;LLVMRemarks;general;LLVMScalarOpts;general;LLVMSupport;general;LLVMTarget;general;LLVMTransformUtils;general;LLVMipo;
LLVM_ENABLE_LTO:STRING=OFF
LLVM_TOOL_LLVM_LTO2_BUILD:BOOL=ON
LLVM_TOOL_LLVM_LTO_BUILD:BOOL=ON
LLVM_TOOL_LTO_BUILD:BOOL=ON
LLVMgold_LIB_DEPENDS:STATIC=general;LLVMX86CodeGen;general;LLVMX86AsmParser;general;LLVMX86Desc;general;LLVMX86Disassembler;general;LLVMX86Info;general;LLVMLinker;general;LLVMLTO;general;LLVMBitWriter;general;LLVMipo;
LTO_LIB_DEPENDS:STATIC=general;LLVMX86AsmParser;general;LLVMX86CodeGen;general;LLVMX86Desc;general;LLVMX86Disassembler;general;LLVMX86Info;general;LLVMBitReader;general;LLVMCore;general;LLVMCodeGen;general;LLVMLTO;general;LLVMMC;general;LLVMMCDisassembler;general;LLVMSupport;general;LLVMTarget;
CMAKE_DLLTOOL-ADVANCED:INTERNAL=1
COMPILER_RT_HAS_FNO_LTO_FLAG:INTERNAL=1
LLVM_TOOL_LLVM_LTO2_BUILD-ADVANCED:INTERNAL=1
LLVM_TOOL_LLVM_LTO_BUILD-ADVANCED:INTERNAL=1
LLVM_TOOL_LTO_BUILD-ADVANCED:INTERNAL=1

$ egrep -i 'pgo|lto' ../../logs/log_tc-build.txt 
-- Performing Test COMPILER_RT_HAS_FNO_LTO_FLAG
-- Performing Test COMPILER_RT_HAS_FNO_LTO_FLAG - Success
```

Some information of my `build-environment`:
```
[ clang ]

$ clang-11 -v
Debian clang version 11.0.0-++20200827023347+522d80ab553-1~exp1~20200827124024.70
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

[ tc-build Git ]

$ git log -1 --oneline 
05e7f327cb3a (HEAD -> master, origin/master, origin/HEAD) Merge pull request #108 from nathanchance/kernel-script-update

[ llvm-project Git ]

$ git branch --show-current 
release/11.x
$ git log -1 --oneline 
97ac9e82002d (HEAD -> release/11.x, origin/release/11.x) [SSP] Restore setting the visibility of __guard_local to hidden for better code generation.
```

Installed Debian `llvm-toolchain-11` packages:
```
VER="1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70"

root# dpkg -l | grep $VER | awk '/^ii/ {print $1 " " $2 " " $3}' | column -t
ii  clang-11                1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  libclang-common-11-dev  1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  libclang-cpp11          1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  libclang1-11            1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  libllvm11:amd64         1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  lld-11                  1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  llvm-11                 1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
ii  llvm-11-runtime         1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.70
```

Do I miss to install some Debian packages?

Do I need a host clang compiler with special support enabled?
How can I verify if my host clang compiler supports PGO and/or ThinLTO?

If this is a `multi-stage` build will I see `PGO` and/or `(Thin)LTO` settings later in a `build/stage2` directory?

**Comment by dileks** [comment]
`build-llvm.py --help` says:
```
[ --pgo ]
Build the final compiler with PGO...

[ --lto LTO_TYPE ]
Build the final compiler with either ThinLTO (thin) or  full LTO (full)...
```

What means `final compiler` in which stage - `post-stage1` - how `many stages` do we pass?

**Comment by nathanchance** [comment]
> [ My first question ]
> Why is it possible to set `stage1-only` tc-build options when I do a PGO + ThinLTO build which is AFAICS a `multi-stage` build?

I could probably change this like I did for the clone options so that the script errors if you try to do `--build-stage1-only` + `--pgo`/`--lto=thin`/`--lto=full`.

> [ My second question ]
> How can I verify that especially `PGO` (and ThinLTO) was enabled?

Grep for `LLVM_PROFDATA_FILE` and `LLVM_ENABLE_LTO` in the `stage3` build folder.

> Do I need a host clang compiler with special support enabled?

No.

> How can I verify if my host clang compiler supports PGO and/or ThinLTO?

As far as I am aware, all recent versions of clang support these.

> If this is a `multi-stage` build will I see `PGO` and/or `(Thin)LTO` settings later in a `build/stage2` directory?

For PGO, you will have three stages; the bootstrap compiler, the instrumented compiler, and the final compiler.

**Comment by nathanchance** [comment]
Re-reading the way that we have things set up, `--lto=thin` or `--lto=full` can be used with `--build-stage1-only`. I am not sure that I like this idea because it can result in cryptic failures at times (due to depending on the user's environment rather than the bootstrap environment) but I am not going to restrict it for now. I have added a note to the help text that doing this combination is discouraged.

For now, I have pushed #110, which should prevent `--pgo` and `--build-stage1-only` from being used together.

**Comment by dileks** [comment]
Aaargh...

I do not want to build a Linux-kernel!
Just the toolchain...

```
[2959/2959] Linking CXX static library lib/libLLVMTestingSupport.a
curl: (6) Could not resolve host: cdn.kernel.org
sha256sum: linux-5.8.3.tar.xz: No such file or directory
linux-5.8.3.tar.xz: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
Linux tarball verification failed! Please remove '/home/dileks/src/llvm-toolchain/git/kernel/linux-5.8.3.tar.xz' and try again.

========================
== Checking CC and LD ==
========================

CC: /usr/lib/llvm-11/bin/clang
CXX: /usr/bin/clang++-11
LD: /usr/bin/ld.lld-11

===========================
== Checking dependencies ==
===========================

/usr/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/bin/ninja

==============================
== Configuring LLVM stage 1 ==
==============================


===========================
== Building LLVM stage 1 ==
===========================


LLVM build duration: 2:36:17

==============================
== Configuring LLVM stage 2 ==
==============================


===========================
== Building LLVM stage 2 ==
===========================


LLVM build duration: 2:10:01

===========================
== Building PGO profiles ==
===========================

Traceback (most recent call last):
  File "./build-llvm.py", line 1008, in <module>
    main()
  File "./build-llvm.py", line 1004, in main
    do_multistage_build(args, dirs, env_vars)
  File "./build-llvm.py", line 978, in do_multistage_build
    generate_pgo_profiles(args, dirs)
  File "./build-llvm.py", line 945, in generate_pgo_profiles
    subprocess.run([
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[PosixPath('/home/dileks/src/llvm-toolchain/git/kernel/build.sh'), '-b', PosixPath('/home/dileks/src/llvm-toolchain/build'), '--pgo', 'true', '-t', 'X86']' returned non-zero exit status 1.
```

**Comment by dileks** [comment]
Can I suppress this, please.

**Comment by nathanchance** [comment]
Then don't use `--pgo`. The entire premise of PGO is that you tune the compiler towards a specific workload. In tc-build's case, that is building kernels so we HAVE to build at least one kernel to get profile data that can be used to tune the compiler. If that is not something that you want to do, you cannot use `--pgo`.

**Comment by dileks** [comment]
OK, that makes sense.

What is built - a defconfig-ed kernel?

**Comment by nathanchance** [comment]
Yes, just a `defconfig` for each architecture provided by `--targets`. So in your case, just `x86_64_defconfig`.

I could potentially look into providing profiles in a similar way that [Android does](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master/profiles/) but that is something for a later point in time plus it could be harmful to use a profile from a different version of clang than the one being currently built...

**Comment by dileks** [comment]
Remember the PGO talks - yes you need PGO profdata.
Can we enhance the help text in build-llvm.py?

**Comment by dileks** [comment]
Re-invoking my build-script - stage2 is not ccache-ed.

**Comment by dileks** [comment]
That's really disgusting. You need an Internet connection and stage2 is not ccached - take me 02:30 of build-time for stage2 again.

This needs to be in the help-text as well.

**Comment by dileks** [comment]
Help-text should also point to this a `3-stage` build. An information to build-time and disc-usage desired, too.

I hoped I could start a new kernel build with the new LLVM toolchain out of my local Git.

**Comment by dileks** [comment]
If I have a local linux-git I want to use that - not downloading a tarball.

**Comment by dileks** [comment]
3x 02:30 (or 02:45) for 3 stages for the final toolchain plus build-time of defconfig-ed Linux v5.8.3?
Guys, you are kidding?

**Comment by nathanchance** [comment]
Can you read #110 before commenting further and see what you think?

`ccache` would not help you even if it was enabled because you are rebuilding stage 1 so the cache would not hit. [From `ccache`'s documentation](https://ccache.dev/manual/3.7.11.html#_common_hashed_information), the modification time of the compiler is included in the hash. I am not sure why I would need to call that out in the help text. Honestly, if time and resources matter to you, compiling with PGO is probably not worthwhile...

> If I have a local linux-git I want to use that - not downloading a tarball.

For what it's worth, if you move that into the `kernel` folder, it will just unpack it instead of trying to download it. I can add a `--linux-src` option to `build-llvm.py` if it would be useful to you.

> 3x 02:30 (or 02:45) for 3 stages for the final toolchain plus build-time of defconfig-ed Linux v5.8.3?
> Guys, you are kidding?

I really do not appreciate the seemingly aggressive tone that you have here. I am sorry if you are frustrated from wasted time and resources but there is not really a way to optimize this process more than it is. We have to build an instrumented compiler, build a kernel with it, then build the final compiler. The first stage is not _strictly_ necessary but I do not like the idea of adding a `--do-pgo-in-two-stages` option.

That is why I posted [the benchmark results that I did](https://gist.github.com/nathanchance/3ac507d20850a02172a083148809f63b). If you had looked those over, you would see that PGO is going to increase your overall build time by 5x... I never claimed this was a trivial or inexpensive procedure.

**Comment by dileks** [comment]
I need to calm down first.

**Comment by dileks** [comment]
#110 is an improvement but lacks IMHO clear words that build-time and disc-usage will be increased - with some real stats.

Dunno if this is 5x build-time of a stage-only build - I have no experiences.
What's with the disc-usage - compared to stage1 for example?
Be userfriendly and give some numbers?

**Comment by dileks** [comment]
Sorry, I will stop this...
Some Clang-CFI patches from Sami I waited for.

**Comment by nathanchance** [comment]
I am going to be out for a few hours but I will try to improve #110 based on your feedback when I get back.

I am not going to be able to provide raw numbers though because my hardware is different from yours. I will do my best to spell out exactly what the process will be succinctly in the help text to help users make their own decisions about if it is worthwhile or not.

Thanks for the feedback!

**Comment by dileks** [comment]
I mean we can give numbers compared to a stage1-only build?

Disc-usage should not matter on hardware?

**Comment by nathanchance** [comment]
Disk usage can vary based on the configuration options and number of kernels built. Again, the idea is not to be exact but give a rough ballpark. Would you have still tried it if I said it would take you eight hours versus ten hours compared to your regular two and a half hours?

**Comment by dileks** [comment]
I killed my build directory right now.

Remember when I looked into it:

stage1 dir was created 17:34
stage2 dir was created 20:10

So this means to me 02:36 for a stage1 build on my hardware.

**Comment by dileks** [comment]
If we can offer "PGO training data" for x86-64 arch that would be a huge improvement, too.
Unsure if this data can be hardware independent or not.

**Comment by dileks** [comment]
@nathan

It was not my intention to offend you. I apologize if I did.

**Comment by nathanchance** [comment]
No worries, I understand the frustration of waiting for something to get done building and have an error somewhere in the middle :) your feelings were valid and I will take the feedback to improve the documentation so that there is no more miscommunication!

**Comment by ojeda** [comment]
In my bachelor's degree I spent many spring evenings building a Linux disk image to perform some research on a SPARC full system emulator. I was building GCC as a cross-compiler and then building everything else needed for the image using that one, without access to a SPARC Linux machine or a native GCC. At the time, such a proposition was painful to say the least so basically you needed to try combinations of GCC/dependencies and flags too to find one that worked (or use one that somebody found).

Thus everything from scratch, and it should be reproducible, so I made a script to do it all. Each run took long enough that I basically left my script going on through the night, then trying again next time I passed by the department.

So... I understand the frustration too, but think about it in another way: with this tool it is basically done, tested and documented for you, and if it fails, nowadays it is easy to contact just about everyone! :)

**Comment by nathanchance** [comment]
Alright, I think that #110 should address everything that I have gathered from this issue, please take a look!

**Comment by dileks** [comment]
Thanks @nathanchance 

OK, I see the numbers `50 GBytes of disc-space` plus `5x of speed of a stage1-only build`.

Thanks for the `--linux-folder` tc-build option.
Does the PGO process - when gathering data from the build of the Linux-kernel needs a `make distclean` before or do I need to do that myself?
Where are `PGO training data` stored - in the `--linux-folder` directory or within the build-dir (`build/stage3`) of tc-build?

P.S.: Just finished my build from Sami's Clang-CFI - boots now on bare metal without any CFI failures.

**Comment by nathanchance** [comment]
> OK, I see the numbers `50 GBytes of disc-space` plus `5x of speed of a stage1-only build`.

I actually ended up lowering it to 25GB based on my actual measurements (that number was a placeholder) and that is probably on the higher side anyways so it should work out.

> Does the PGO process - when gathering data from the build of the Linux-kernel needs a `make distclean` before or do I need to do that myself?

It will run `make distclean` for you automatically because we need fresh results.

> Where are `PGO training data` stored - in the `--linux-folder` directory or within the build-dir (`build/stage3`) of tc-build?

It is stored within the `build` folder (not any of the stages).

> P.S.: Just finished my build from Sami's Clang-CFI - boots now on bare metal without any CFI failures.

Awesome! :)

**Comment by dileks** [comment]
@nathanchance 

Will you update your proposed patches in #110 (speaking of disc-usage approx. 25GiB vs. 50GiB)?

**Comment by nathanchance** [comment]
It should be updated: https://github.com/ClangBuiltLinux/tc-build/pull/110/commits/6026314b200600b043633751ed0b0800bfbb3c21

**Comment by dileks** [comment]
@nathanchance /o\

**Comment by dileks** [comment]
The build of `ThinLTO` happens in which stage? `stage2`?

**Comment by nathanchance** [comment]
Whatever the final stage is (so stage 3 for `--pgo`, stage 2 by default, or stage 1 for `--build-stage1-only`).

**Comment by dileks** [comment]
`stage1` and `stage3` is now clear to me.

But not where the `LTO` build happens?

**Comment by nathanchance** [comment]
LTO is done at the final stage so that the installed compiler is the most optimized. So if you are using `--pgo`, LTO will be done at stage 3 (the final one) in addition to PGO. Hopefully that makes sense.

**Comment by dileks** [comment]
Thanks for everything.

I start a new LLVM toolchain build.

**Comment by dileks** [comment]
@nathanchance 

Same code base of `Clang-CFI` from @samitolvanen Git with the identicial `kernel-config`:
```
[ Debian's LLVM toolchain version 1:11.0.0~++20200827023347+522d80ab553-1~exp1~20200827124024.7 ]

$ tail -20 5.9.0-rc2-7-amd64-clang-cfi/build-log_5.9.0-rc2-7-amd64-clang-cfi.txt
 Performance counter stats for 'make V=1 -j3 HOSTCC=clang-11 HOSTCXX=clang++-11 HOSTLD=ld.lld-11 HOSTAR=llvm-ar-11 CC=clang-11 LD=ld.lld-11 AR=llvm-ar-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11 LLVM_IAS=1 LOCALVERSION=-7-amd64-clang-cfi KBUILD_VERBOSE=1 KBUILD_BUILD_HOST=iniza KBUILD_BUILD_USER=sedat.dilek@gmail.com KBUILD_BUILD_TIMESTAMP=2020-08-29 bindeb-pkg KDEB_PKGVERSION=5.9.0~rc2-7~bullseye+dileks1':

       60901314.78 msec task-clock:u              #    2.989 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
         407276173      page-faults:u             #    0.007 M/sec                  
   114756294117526      cycles:u                  #    1.884 GHz                    
    92003100350407      stalled-cycles-frontend:u #   80.17% frontend cycles idle   
    73938848736116      stalled-cycles-backend:u  #   64.43% backend cycles idle    
    69694700676328      instructions:u            #    0.61  insn per cycle         
                                                  #    1.32  stalled cycles per insn
    13515316398504      branches:u                #  221.922 M/sec                  
      578071086885      branch-misses:u           #    4.28% of all branches        

   20377.154661501 seconds time elapsed

   58269.458483000 seconds user
    2712.689816000 seconds sys

[ Selfmade LLVM toolchain version 97ac9e82002d6b12831ca2c78f739cca65a4fa05 - ThinLTO and PGO optimized ]

$ tail -20 5.9.0-rc2-8-amd64-clang-cfi/build-log_5.9.0-rc2-8-amd64-clang-cfi.txt
 Performance counter stats for 'make V=1 -j3 HOSTCC=clang-11 HOSTCXX=clang++-11 HOSTLD=ld.lld-11 HOSTAR=llvm-ar-11 CC=clang-11 LD=ld.lld-11 AR=llvm-ar-11 NM=llvm-nm-11 OBJCOPY=llvm-objcopy-11 OBJDUMP=llvm-objdump-11 OBJSIZE=llvm-size-11 READELF=llvm-readelf-11 STRIP=llvm-strip-11 LLVM_IAS=1 LOCALVERSION=-8-amd64-clang-cfi KBUILD_VERBOSE=1 KBUILD_BUILD_HOST=iniza KBUILD_BUILD_USER=sedat.dilek@gmail.com KBUILD_BUILD_TIMESTAMP=2020-08-29 bindeb-pkg KDEB_PKGVERSION=5.9.0~rc2-8~bullseye+dileks1':

       40040971.54 msec task-clock:u              #    2.947 CPUs utilized          
                 0      context-switches:u        #    0.000 K/sec                  
                 0      cpu-migrations:u          #    0.000 K/sec                  
         303166735      page-faults:u             #    0.008 M/sec                  
    74400852707817      cycles:u                  #    1.858 GHz                    
    54896036594491      stalled-cycles-frontend:u #   73.78% frontend cycles idle   
    39410178557877      stalled-cycles-backend:u  #   52.97% backend cycles idle    
    62555776655790      instructions:u            #    0.84  insn per cycle         
                                                  #    0.88  stalled cycles per insn
    11100181464287      branches:u                #  277.221 M/sec                  
      469724159064      branch-misses:u           #    4.23% of all branches        

   13587.149983741 seconds time elapsed

   37994.759048000 seconds user
    2116.255661000 seconds sys
```

Very impressive numbers: `20377.154661501 seconds` VS. `13587.149983741 seconds` means `-33,33% of build-time`.

**Comment by dileks** [comment]
More numbers in MiB (with *no* download of the Linux release tarball):
```
[ tc-build ]
python3 ./build-llvm.py --no-update --build-type Release -p clang;lld -t X86 --clang-vendor '' -B /home/dileks/src/llvm-toolchain/build -I /home/dileks/src/llvm-toolchain/install --check-targets clang lld -L /home/dileks/src/linux-kernel/git --lto thin --pgo

[ disc-space ]
7939    /home/dileks/src/llvm-toolchain/build
1343    /home/dileks/src/llvm-toolchain/install
540     /home/dileks/src/linux-kernel/git/out
===============================================
Total: 9822
```

**Comment by dileks** [comment]
I had the benefit of `stage1` was `ccache-ed` means `02:36 saving of build-time` (needs to be added):
```
[ tc-build log-file ]
LLVM build duration: 9:00:33
```
So the real `build-time` was approx. `11:30`.

Looking at the time-stamps of some directories:
```
$ LC_ALL=C ls -alth ~/src/llvm-toolchain/build ~/src/llvm-toolchain/install
/home/dileks/src/llvm-toolchain/install:
total 28K
drwxr-xr-x 11 dileks dileks 4.0K Aug 29 21:00 ..
drwxr-xr-x  2 dileks dileks 4.0K Aug 29 20:32 bin
drwxr-xr-x  6 dileks dileks 4.0K Aug 29 20:32 .
-rw-r--r--  1 dileks dileks    1 Aug 29 20:32 .gitignore
drwxr-xr-x  4 dileks dileks 4.0K Aug 29 20:32 lib
drwxr-xr-x  4 dileks dileks 4.0K Aug 29 20:32 share
drwxr-xr-x  7 dileks dileks 4.0K Aug 29 20:32 include

/home/dileks/src/llvm-toolchain/build:
total 26M
drwxr-xr-x 11 dileks dileks 4.0K Aug 29 21:00 ..
drwxr-xr-x 14 dileks dileks 4.0K Aug 29 20:32 stage3
drwxr-xr-x  5 dileks dileks 4.0K Aug 29 11:31 .
-rw-r--r--  1 dileks dileks  26M Aug 29 11:31 profdata.prof
drwxr-xr-x 15 dileks dileks 4.0K Aug 29 08:35 stage2
drwxr-xr-x 12 dileks dileks 4.0K Aug 29 08:33 stage1
```

Here you can see the `profdata.prof` file is stored in the `build` directory.

**Comment by dileks** [comment]
I have some more ideas on improving `tc-build` towards `ThinLTO` and especially `PGO` optimized `LLVM toolchain` build.

Examples:
1. Add make verbosity like `make V=1` for the kernel-build process - as a separate option?
1. `/path/to/linux-dir` (`-L` option) was not cleaned - unsure if this is intended.

**Comment by dileks** [comment]
For posterity and the ensuing ages:
```
$ cat /proc/version 
Linux version 5.9.0-rc2-8-amd64-clang-cfi (sedat.dilek@gmail.com@iniza) (clang version 11.0.0 (https://github.com/llvm/llvm-project 97ac9e82002d6b12831ca2c78f739cca65a4fa05), LLD 11.0.0 (https://github.com/llvm/llvm-project 97ac9e82002d6b12831ca2c78f739cca65a4fa05)) #8~bullseye+dileks1 SMP 2020-08-29
```

**Comment by dileks** [comment]
Small typo in the pushed commit `s/--linux-src/--linux-folder`:
```
+    parser.add_argument("-L",
+                        "--linux-folder",
...
+                        3. Download and extract kernel source from kernel.org (unless '--linux-src' is
```

**Comment by dileks** [comment]
Sidenote:
Maybe mention only for the stage1 build ccache makes sense and will be used there.
Unsure where to place such an information.

**Comment by nathanchance** [comment]
Pushed #111 to address both comments.
