### ISSUE TITLE
Debug: Add verbosity to cmake (LLVM) and make (Linux) options

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#112]
Last weekend I finished a marathon in building a `ThinLTO and PGO optimized` `LLVM toolchain` - optimized here means for `Linux v5.9-rc2` with `Clang-CFI` enabled (details see [0] and especially my request on this one here in [1]).

While gasping at the the following section:
```
==  Building kernels  ==
========================

+ for TARGET in "${TARGETS[@]}"
+ case ${TARGET} in
+ make -skj4 O=out LLVM=1 distclean defconfig bzImage modules

real    45m56.082s
user    166m53.758s
sys     8m11.487s

$ du -s -m ~/src/linux-kernel/git/out
540     /home/dileks/src/linux-kernel/git/out
```

Several minutes you do not get a feedback.

For me watching the `make V=1` lines of a Linux-kernel build is psychologically fundamental - it calms me down - and besides helpful to see what's going on and warnings etc.

Same can be done for `cmake ` and the `LLVM` build-process (where I am personally and psychologically not interested).

Can we rename `Building kernels` to `Building Linux` and remove the double space to be consistent with the other section names?
```
$ grep '^\==  Building' log_tc-build.txt
==  Building kernels  ==

$ grep '^\== Building' log_tc-build.txt
== Building LLVM stage 1 ==
== Building LLVM stage 2 ==
== Building PGO profiles ==
== Building LLVM stage 3 ==
```

Side-note: Shouldn't this be named "Generating PGO profiles"?

[0] https://github.com/ClangBuiltLinux/tc-build/issues/109
[1] https://github.com/ClangBuiltLinux/tc-build/issues/109#issuecomment-683355211
[2] https://github.com/samitolvanen/linux/commits/clang-cfi

**Comment by msfjarvis** [comment]
Well,

<details>
<summary>Short answer</summary>

![image](https://user-images.githubusercontent.com/13348378/91826834-bc16a080-ec5b-11ea-981c-d67330c032f3.png)


</details>

Longer answer: Building the kernel is a profiling task, and what goes on during the actual build is inconsequential in the grand scheme of things: building a Clang compiler. I can't answer for your psychological requirements, but to keep track of what's happening in the kernel build you can simply use `htop` to monitor `make` calls. What you're looking for is an extremely niche requirement that's not useful to other tc-build users so I'd recommend simply carrying a local patch for `make V=1` if its important to you. I'll look into the formatting issues.

**Comment by dileks** [comment]
A tc-build option is much appreciated - it's up to the user can use it or not.
I do not like carrying local patches if not necessarily needed.

P.S.: I was thinking of... when a LLVM or Linux build breaks somewhere.

**Comment by msfjarvis** [comment]
> A tc-build option is much appreciated - it's up to the user to use/set it or not.
> I do not like carrying local patches if not necessarily needed.

Adding options upstream for every requirement from every user is not tenable, we're not cURL and can't be shipping 200+ command line flags. A line has to be drawn somewhere.

> P.S.: I was thinking of... when a LLVM or Linux build breaks somewhere.

Then a manual rebuild of the kernel to fully triage the problem for filing an issue will be required regardless, so that doesn't really convince me of its utility. When LLVM build breaks you'll be able to see it because those logs are not filtered out.

**Comment by nathanchance** [comment]
There comes a point where options become too niche or not useful for the general population. I believe that this request is at that point. Others are free to disagree with me and push a patch for review though.

`make -s` still shows warnings and errors, so does just regular `cmake` + `ninja`. I do not see any real tangible benefits to a `--debug`, especially given I have used the script for a LOT of stuff and never felt I was missing that option.

**Comment by dileks** [comment]
What a pity... I can carry a `make V=1` patch when not favoured.

Formatting/Renaming of `==  Building kernels  ==` would be nice.

**Comment by msfjarvis** [comment]
> P.S.: Why plural `kernels` - AFAICS it is a `single` Linux-kernel build?

Isn't it one kernel per selected architecture?

**Comment by dileks** [comment]
> > P.S.: Why plural `kernels` - AFAICS it is a `single` Linux-kernel build?
> 
> Isn't it one kernel per selected architecture?

Good point. I have a single `x86` target, so I dunno.

**Comment by dileks** [comment]
That should address all my comments...
```diff
diff --git a/build-llvm.py b/build-llvm.py
index fa3dcac09a22..4794d40db8c2 100755
--- a/build-llvm.py
+++ b/build-llvm.py
@@ -981,7 +981,7 @@ def generate_pgo_profiles(args, dirs):
     :return:
     """
 
-    utils.print_header("Building PGO profiles")
+    utils.print_header("Generating PGO profiles")
 
     # Run kernel/build.sh
     build_sh = [
diff --git a/kernel/build.sh b/kernel/build.sh
index f4cf62a6f4d5..5a06b0efa090 100755
--- a/kernel/build.sh
+++ b/kernel/build.sh
@@ -6,7 +6,7 @@ TC_BLD=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"/.. && pwd)
 
 function header() {
     BORDER="====$(for _ in $(seq ${#1}); do printf '='; done)===="
-    printf '\033[1m\n%s\n%s\n%s\n\n\033[0m' "${BORDER}" "==  ${1}  ==" "${BORDER}"
+    printf '\033[1m\n%s\n%s\n%s\n\n\033[0m' "${BORDER}" "== ${1} ==" "${BORDER}"
 }
 
 # Parse parameters
@@ -126,7 +126,7 @@ done
 # shellcheck disable=SC2191
 MAKE=(make -skj"$(nproc)" O=out)
 
-header "Building kernels"
+header "Building Linux"
 
 set -x
  ```

As reported in [1] I only see a single `out` directory for the Linux build here in the `PGO profiles` stage, so I used `singular` in my diff:
```
[ disc-space ]
540     /home/dileks/src/linux-kernel/git/out
```

[1] https://github.com/ClangBuiltLinux/tc-build/issues/109#issuecomment-683353335

**Comment by dileks** [comment]
For `make verbosity` in the Linux building stage:
```
125 # SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.
126 # shellcheck disable=SC2191
-127 MAKE=(make -skj"$(nproc)" O=out)
+127 MAKE=(make V=1 -skj"$(nproc)" O=out)
```

**Comment by dileks** [comment]
Friendly ping.

**Comment by msfjarvis** [comment]
#115 has been filed for the formatting fixes, there is not going to be a debug option in the scripts so I'm closing this issue as resolved.
