### ISSUE TITLE
Option for BPF support when CONFIG_DEBUG_INFO_BTF=y

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#129]
Debian-kernel team started to set `CONFIG_DEBUG_INFO_BTF=y`.

First, this needs `pahole` binary from `dwarves` package (minimum: `v1.16`).
```
$ pahole --version
v1.19
```

Second, your LLVM toolchain needs `BPF support` enabled.

My selfmade LLVM toolchain v11.0.1 does not have this:

```
$ which llc
/home/dileks/src/llvm-toolchain/install/bin/llc

$ llc --version
LLVM (http://llvm.org/):
 LLVM version 11.0.1
 Optimized build.
 Default target: x86_64-unknown-linux-gnu
 Host CPU: sandybridge

 Registered Targets:
   x86    - 32-bit X86: Pentium-Pro and above
   x86-64 - 64-bit X86: EM64T and AMD64
```

Debian's LLC has BPF support:
```
$ /usr/bin/llc-11 --version | grep -i bpf
   bpf        - BPF (host endian)
   bpfeb      - BPF (big endian)
   bpfel      - BPF (little endian)
```

Is it possible to have an option to enable `BPF support`?

Thanks.

[1] https://salsa.debian.org/kernel-team/linux/-/commit/929891281c61ce4403ddd869664c949692644a2f
[2] https://www.kernel.org/doc/html/latest/bpf/bpf_devel_QA.html?highlight=pahole#llvm
[3] https://www.kernel.org/doc/html/latest/bpf/btf.html?highlight=pahole#btf-generation

**Comment by msfjarvis** [comment]
Any issues you see with just having it always enabled instead?

**Comment by dileks** [comment]
It breaks here with `CONFIG_DEBUG_INFO_BTF=y`:
```
+ [ -n y -a -n y ]
+ info BTFIDS vmlinux
+ [  != silent_ ]
+ printf   %-7s %s\n BTFIDS vmlinux
 BTFIDS  vmlinux
+ ./tools/bpf/resolve_btfids/resolve_btfids vmlinux
FAILED: load BTF from vmlinux: Invalid argument
+ on_exit
+ [ 255 -ne 0 ]
+ cleanup
+ rm -f .btf.vmlinux.bin.o
```
https://lists.debian.org/debian-kernel/2021/01/msg00110.html

**Comment by dileks** [comment]
Just FYI:
I started a thread on BPF and linux-kbuild mailing-ist:
`Check pahole availibity and BPF support of toolchain before starting a Linux kernel build`

[1] https://lore.kernel.org/bpf/CA+icZUVuk5PVY4_HoCoY2ymd27UjuDi6kcAmFb_3=dqkvOA_Qw@mail.gmail.com/T/#u
[2] https://marc.info/?l=linux-kbuild&m=161036940824132&w=2

**Comment by dileks** [comment]
@msfjarvis 

Do you have a quick (and dirty) fix?

**Comment by msfjarvis** [comment]
> @msfjarvis 
> 
> Do you have a quick (and dirty) fix?

I do not.

**Comment by dileks** [comment]
`[llvm-dev] BPF: How can I enable BPF support in my LLVM toolchain?`

[1] https://lists.llvm.org/pipermail/llvm-dev/2021-January/147728.html

**Comment by dileks** [comment]
Add `BPF` to `targets`:
```
python3 ./build-llvm.py --no-update --build-type Release -p clang;lld -t X86;BPF --clang-vendor dileks -B /home/dileks/src/llvm-toolchain/build -I /home/dileks/src/llvm-toolchain/install --check-targets clang lld --build-stage1-only --install-stage1-only
```
Logs:
```
-- Targeting X86
-- Targeting BPF
```

**Comment by dileks** [comment]
It might be enough to add a hint to `targets` option in case of BPF?

**Comment by tstellar** [comment]
I ran into this same bug trying to build the Fedora kernel.  The problem is that pahole segfaults at: scripts/link-vmlinux.sh:131.  This looks to me like a bug in pahole.

**Comment by dileks** [comment]
@tstellar 

Which version of `pahole` do you use?

**Comment by dileks** [comment]
`BPF` support looks good:
```
$ ./build/stage1/bin/llc --version
LLVM (http://llvm.org/):
  LLVM version 11.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: sandybridge

  Registered Targets:
    bpf    - BPF (host endian)
    bpfeb  - BPF (big endian)
    bpfel  - BPF (little endian)
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
```

**Comment by tstellar** [comment]
> @tstellar
> 
> Which version of `pahole` do you use?

@dileks 1.19.  This build: https://koji.fedoraproject.org/koji/buildinfo?buildID=1644955

**Comment by dileks** [comment]
@tstellar 

Upstream Git `pahole` has `btf_encoder` fixes - post v1.19.

[1] https://git.kernel.org/pub/scm/devel/pahole/pahole.git/

**Comment by dileks** [comment]
Wow how fast, thanks!

**Comment by JiaHuann** [comment]
Why i meet this again in pahole 1.27.....

**Comment by dileks** [comment]
https://github.com/ClangBuiltLinux/linux/issues/2032
https://github.com/ClangBuiltLinux/linux/issues/2032#issuecomment-2248325906

**Comment by JiaHuann** [comment]
> [ClangBuiltLinux/linux#2032 ](https://github.com/ClangBuiltLinux/linux/issues/2032) [ClangBuiltLinux/linux#2032（评论）](https://github.com/ClangBuiltLinux/linux/issues/2032#issuecomment-2248325906)
Thanks! work for me.

**Comment by JiaHuann** [comment]
> > 为什么我在 pahole 1.27 中再次遇到这种情况......
> 
> Pahole 目前需要修补。现在应该在 -git 中修复了。



> [ClangBuiltLinux/linux#2032 ](https://github.com/ClangBuiltLinux/linux/issues/2032) [ClangBuiltLinux/linux#2032（评论）](https://github.com/ClangBuiltLinux/linux/issues/2032#issuecomment-2248325906)

Thanks. Looks good to me.
