### ISSUE TITLE
[request]Specify the number of compilation threads

### ISSUE THREAD

**Issue by zixijian** [ClangBuiltLinux/tc-build#132]
When compiling in the chroot container of the mobile phone, the heat is severe and the memory is insufficient.
It is recommended to specify the number of threads. A reasonable number of threads will neither cause fever or frequency reduction nor memory explosion.

**Comment by nathanchance** [comment]
If I understand your message correctly (apologies, I am using Google Translate), can you please give this a shot and see if it works?

https://github.com/nathanchance/tc-build/commit/d067c30d553b7d544c4b526339681fb6d21b61ce

To be fair, I would not personally recommend compiling LLVM on your phone :)

**Comment by zixijian** [comment]
> If I understand your message correctly (apologies, I am using Google Translate), can you please give this a shot and see if it works?
> 
> [nathanchance@d067c30](https://github.com/nathanchance/tc-build/commit/d067c30d553b7d544c4b526339681fb6d21b61ce)
> 
> To be fair, I would not personally recommend compiling LLVM on your phone :)

thanks，it worked.

Frankly speaking, mobile phone compilation is not a big problem. 
I have completed the compilation without specifying threads, and compiled the Android kernel using the tool chain.
That's Why I gave feedback and suggestions on my situation.
