### ISSUE TITLE
-fno-semantic-interposition and -Bsymbolic-functions

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/tc-build#158]
-fno-semantic-interposition via https://reviews.llvm.org/D102453 should be enabled now by default IIUC, but IIRC `-Bsymbolic-functions` got reverted (cc @MaskRay ).  I'm curious if these make a difference once statically linking though (#150 )

**Comment by nickdesaulniers** [comment]
> I'm curious if these make a difference once statically linking though

[It's not](https://github.com/ClangBuiltLinux/tc-build/issues/150#issuecomment-849935207), but until we are statically linking, perhaps they are still interesting.

**Comment by MaskRay** [comment]
`-Bsymbolic-functions` for libLLVM-13git.so and libclang-cpp.so was re-committed in <https://reviews.llvm.org/D102090>

`-fno-semantic-interposition` was committed separately today.

ELF platforms get the benefits automatically, no need for additional CMake options.
