### ISSUE TITLE
CMake build error in ./build-llvm.py on Ubuntu Bionic

### ISSUE THREAD

**Issue by mcdachpappe** [ClangBuiltLinux/tc-build#163]
**Describe the bug**
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.13.4 or higher is required.  You are running version 3.10.2

Readme (https://github.com/ClangBuiltLinux/tc-build/blob/main/README.md) says that Ubuntu Bionic is supported but latest CMake version for Bionic is 3.10.2.

**To Reproduce**
1. Run ./build-llym.py
2. See error

**Expected behavior**
Script success.

**Environment (please complete the following information):**
  - Command you ran: ./build-llvm.py
  - Distribution: Ubuntu Bionic 18.04.5
  - Python version: python3.6 2

**Comment by nathanchance** [comment]
Thanks for the report, looks like upstream LLVM updated the minimum cmake version a little over a year ago: https://github.com/llvm/llvm-project/commit/afa1afd4108d973e059e5f5ad68cf01efe7985da

I will update the README to clarify that the latest version of Debian and Ubuntu should be used whenever possible: https://github.com/ClangBuiltLinux/tc-build/pull/164

If you cannot upgrade to a more recent version of Ubuntu, you can either [build `cmake` from source or download a prebuilt binary](tps://cmake.org/install/) but you do risk running into other build issues if the other tools are not up to date.
