### ISSUE TITLE
[BOLT] Minimum hardware requirements?

### ISSUE THREAD

**Issue by torvic9** [ClangBuiltLinux/tc-build#188]
Hi,

Out of curiosity I gave BOLT (without PGO) a try, on a Zen2 platform with 32 GB of RAM, building from the 14.x branch.
Everything went well until the last step, when at some point the build process was SIGKILLed.
I was away from keyboard and didn't the save the build log, but I guess it was simply a OOM situation - the fdata profile was a whopping 128 GB after all. The profile merge log didn't show any errors.

So it seems that 32 GB are not enough, at least on Zen with llvm-bolt. The script is already well documented, but maybe add a line or two about RAM requirements.

On a sidenote, when using BOLT, does it matter whether the first stage is built with either GCC or Clang, and does using ccache have an influence on the further build process?

(EDIT: This computer only has swap via Zram but no disk based swap file or partition. Maybe adding more swap could help?)

**Comment by nathanchance** [comment]
> I currently have no access to that computer, but from the top of my head, build options were as follows:

Thanks, I will see if I can reproduce.

> I didn't enable PGO in this test because the build process is already slow enough without it ;-)

Personally, I would recommend swapping `--lto thin` for `--pgo kernel-defconfig`. I did a pretty extensive set of benchmarks a couple of years ago that showed that PGO will give you a bigger performance lift at kernel compile time than ThinLTO will for less LLVM compile time, especially if you are only care about the x86 backend, as you only have to build one kernel, rather than multiple ones.

https://gist.github.com/nathanchance/976cb6f7bc5b630e7dd15b539d4e8040

https://github.com/ClangBuiltLinux/CBL-meetup-2020-slides/blob/master/nathan/Exploring_Speeding_Up_a_Linux_Kernel_Build_with_LLVM_Tools_and_Technologies.pdf

> Will also monitor the build process more closely, as I'm still not sure what caused the SIGKILL.

I have been pretty enamored with [`btop`](https://github.com/aristocratos/btop) for resource monitoring, it was helpful when looking at the BOLT process because I could see how much memory `perf` was using (not relevant here as Zen 2 has to use instrumentation).

**Comment by nathanchance** [comment]
With ThinLTO:

```
Command being timed: "/home/nathan/Dev/cbl/github/tc-build/build-llvm.py --assertions --bolt --check-targets clang lld llvm llvm-unit --lto thin --pgo kernel-defconfig --show-build-commands --targets X86"
User time (seconds): 77198.41
System time (seconds): 5389.33
Percent of CPU this job got: 1393%
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:38:46
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 16771864
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 10139655
Minor (reclaiming a frame) page faults: 678638273
Voluntary context switches: 22083973
Involuntary context switches: 15008920
Swaps: 0
File system inputs: 339095496
File system outputs: 399239880
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0
```

So 16.77GB of RAM used, compared to 15.28GB without ThinLTO. Well below 32GB so I suspect something else is going on here.

**Comment by torvic9** [comment]
`Maximum resident set size (kbytes): 30386784`

Without PGO, without LTO.

Here is the actual Python error message:

```
Merging .fdata files, this might take a while...
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: 1f9140064dfbfb0bbda8e51306ea51080b2f7aac
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling lite mode
BOLT-WARNING: Failed to analyze 2914 relocations
BOLT-INFO: pre-processing profile using branch profile reader
Traceback (most recent call last):
  File "/mnt/data/build/github/tc-build/./build-llvm.py", line 1575, in <module>
    main()
  File "/mnt/data/build/github/tc-build/./build-llvm.py", line 1571, in main
    do_multistage_build(args, dirs, env_vars)
  File "/mnt/data/build/github/tc-build/./build-llvm.py", line 1363, in do_multistage_build
    invoke_ninja(args, dirs, stage)
  File "/mnt/data/build/github/tc-build/./build-llvm.py", line 1217, in invoke_ninja
    do_bolt(args, dirs)
  File "/mnt/data/build/github/tc-build/./build-llvm.py", line 1484, in do_bolt
    subprocess.run(clang_opt_cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[PosixPath('/mnt/vbox/Clang/stage1/bin/llvm-bolt'), '--data=/mnt/vbox/Clang/clang.fdata', '--reorder-blocks=cache+', '--reorder-functions=hfsort+', '--split-functions=3', '--split-all-cold', '--dyno-stats', '--icf=1', '--use-gnu-stack', '-o', PosixPath('/home/archon/Install/bin/clang.bolt'), PosixPath('/home/archon/Install/bin/clang-14')]' died with <Signals.SIGKILL: 9>.
```

**Comment by nathanchance** [comment]
Hmmm, that is interesting... With just `--bolt` on my machine:

```
Command being timed: "/home/nathan/Dev/cbl/github/tc-build/build-llvm.py --bolt --check-targets clang lld llvm llvm-unit"
User time (seconds): 33695.32
System time (seconds): 4311.29
Percent of CPU this job got: 1335%
Elapsed (wall clock) time (h:mm:ss or m:ss): 47:25.58
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 17699656
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 11578704
Minor (reclaiming a frame) page faults: 711574924
Voluntary context switches: 19998586
Involuntary context switches: 14486020
Swaps: 0
File system inputs: 238739936
File system outputs: 286802368
Socket messages sent: 0
Socket messages received: 0
Signals delivered: 0
Page size (bytes): 4096
Exit status: 0
```

Little bit larger than before at `17.66GB` but still. Let me try the `release/14.x` branch, I just realized I have been using the main branch for this whole process.

**Comment by nathanchance** [comment]
Okay, this is reproducible at `release/14.x`:

```
$ diskus clang.fdata
126.12 GB (126,116,876,288 bytes)
```

Compared with a recent `main`:

```
$ diskus clang.fdata
150.43 MB (150,429,696 bytes)
```

Looking through the list of BOLT changes in main only, I see https://github.com/llvm/llvm-project/commit/7d7771f34d14e0108adf02a6fd0b33943afae3da, which explains this difference. That change applies cleanly to `release/14.x` and resolves the issue, so I have requested a backport for it:

https://github.com/llvm/llvm-project/issues/55234

Regardless of how that request goes, I have added a note about it to the BOLT help text:

https://github.com/ClangBuiltLinux/tc-build/pull/189

**Comment by torvic9** [comment]
Thank you Nathan!
With that commit applied on top of 14.x, the build runs through without error messages and without OOM. I haven't tested the resulting clang yet though, but will do so.
