### ISSUE TITLE
Ability to specify llvm sha

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/tc-build#193]
**Describe the bug**
Ability to specify llvm sha.

**Expected behavior**
Similar to `--use-good-revision`; I'd like to be able to specify the revision of LLVM we snap to. I think that might make the pgo data more portable for offline training

**Comment by nathanchance** [comment]
`--branch` will do this, as noted in its help text. I guess maybe it should be renamed to be more obvious but I am not sure what that should be.
