### ISSUE TITLE
Use sccache to speed up builds

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#200]
When looking at `LLVM release/15.x` Git branch I noticed the usage of `sccache`:

commit 858ded9cba11aa108eaa67433983cb3af14f6fbf
"workflows: Use sccache to speed up CI builds"

```
cmake_args: '-GNinja -DLLVM_ENABLE_PROJECTS="${{ inputs.projects }}" -DCMAKE_BUILD_TYPE=Release -DLLDB_INCLUDE_TESTS=OFF -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache'
```

Personally, I have no experience with it.

Maybe, it helps us to speedup at least stage1-only builds where `ccache` is used.

I will try with planned `LLVM version 15.0.0-rc1` this week.

Note: I had no look at the current code of tc-build as I have archived my local Git due to disc-usage and other reasons.

[1] https://github.com/llvm/llvm-project/commit/858ded9cba11aa108eaa67433983cb3af14f6fbf

**Comment by dileks** [comment]
There are prebuilt binaries available.

[1] https://github.com/mozilla/sccache/releases/tag/v0.3.0

**Comment by nathanchance** [comment]
> Maybe, it helps us to speedup at least stage1-only builds where `ccache` is used.

It sounds like `sccache` is slower than `ccache` when used locally? https://github.com/mozilla/sccache/issues/160

The main allure of `sccache` over `ccache` to me seems like Rust support and cloud storage support, both of which seem irrelevant for tc-build. Storing the cache in a cloud bucket but having the repo, build objects, and final toolchain be local doesn't make much sense to me.

**Comment by dileks** [comment]
Thanks, Nathan.

Looks like using...
1. compression
2. direct-mode
...has an impact on performance.
ccache with enabled compression and disabled direct-mode gives approx. same performance as sccache.

`Add support for an equivalent to ccache direct mode #219`
https://github.com/mozilla/sccache/issues/219

**Comment by dileks** [comment]
If this is not suitable for tc-build it might be helpful for the CBL CI?

**Comment by nathanchance** [comment]
TuxSuite does use `sccache` in its backend, as TuxMake has support for it built in.

I don't think this makes sense for tc-build so I am closing this.
