### ISSUE TITLE
Linux sources: Download XZ tarball, simplify decompressing and verify sign-file

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#26]
For downloading better use the *.tar.xz as tarball (here: saves approx. 50MiB):
```
linux-5.2.tar.gz                                   08-Jul-2019 04:47    157M
linux-5.2.tar.xz                                   08-Jul-2019 04:47    102M
```

Sidenote: There is also a sign-file around. I have seen a signature-verify part in tc-build. Maybe we can have this here for the Linux sources, too.
```
linux-5.2.tar.sign                                 08-Jul-2019 04:47     983
```

Simplify decompressing of tarballs (modern tar versions are smart enough):
```
tar -xf $tarball
```

Snippet:
```diff

diff --git a/kernel/build.sh b/kernel/build.sh
index 3a9a08576e17..cb8be792973c 100755
--- a/kernel/build.sh
+++ b/kernel/build.sh
@@ -47,7 +47,7 @@ if [[ -n ${SRC_FOLDER} ]]; then
     cd "${SRC_FOLDER}" || exit 1
 else
     LINUX=linux-5.1
-    LINUX_TARBALL=${TC_BLD}/kernel/${LINUX}.tar.gz
+    LINUX_TARBALL=${TC_BLD}/kernel/${LINUX}.tar.xz
     LINUX_PATCH=${TC_BLD}/kernel/${LINUX}.patch
 
     # If we don't have the source tarball, download it
@@ -55,7 +55,7 @@ else
 
     # If there is a patch to apply, remove the folder so that we can patch it accurately (we cannot assume it has already been patched)
     [[ -f ${LINUX_PATCH} ]] && rm -rf ${LINUX}
-    [[ -d ${LINUX} ]] || { tar -xzf "${LINUX_TARBALL}" || exit ${?}; }
+    [[ -d ${LINUX} ]] || { tar -xf "${LINUX_TARBALL}" || exit ${?}; }
     cd ${LINUX} || exit 1
     [[ -f ${LINUX_PATCH} ]] && patch -p1 < "${LINUX_PATCH}"
 fi
```

Just some little improvements.

[1] https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/

**Comment by MSF-Jarvis** [comment]
Can you open a PR with these changes?

**Comment by dileks** [comment]
I tried to get this as pull-request into CBL/tc-build.git via "New pull request" (referencing the branch in [1] via compare) with no success.

[1] https://github.com/dileks/tc-build/tree/linux-source-handling
[2] https://github.com/dileks/tc-build/pull/1

**Comment by MSF-Jarvis** [comment]
> I tried to get this as pull-request into CBL/tc-build.git via "New pull request" (referencing the branch in [1] via compare) with no success.
> 
> [1] [dileks/tc-build@`linux-source-handling`](https://github.com/dileks/tc-build/tree/linux-source-handling)
> [2] [dileks/tc-build#1](https://github.com/dileks/tc-build/pull/1)

You didn't actually create a fork so GitHub didn't offer the option. You'll have to delete the repository, fork it using [this link](https://github.com/ClangBuiltLinux/tc-build/fork), and then do the PR process again.

**Comment by dileks** [comment]
@MSF-Jarvis 

Thanks.
I did not fork but imported the CBL/tc-build.git repo.
See [1] for my pull-request.

[1] https://github.com/ClangBuiltLinux/tc-build/pull/27

**Comment by MSF-Jarvis** [comment]
> @MSF-Jarvis
> 
> Thanks.
> I did not fork but imported the CBL/tc-build.git repo.
> See [1] for my pull-request.
> 
> [1] #27

Thanks for the PR!
