### ISSUE TITLE
objtool warning

### ISSUE THREAD

**Issue by wctrl** [ClangBuiltLinux/tc-build#266]
I'm not sure if this is a bug, but can I ignore `drivers/bluetooth/hci_vhci.o: warning: objtool: .text.vhci_coredump_hdr: unexpected end of section` while building linux 6.6 for x86_64 (I couldn't find any useful information on google)?

Clang build cmdline: `./build-llvm.py --lto thin --use-good-revision --pgo kernel-defconfig -t AArch64 X86 ARM`

**Comment by nathanchance** [comment]
Yes, that is just a warning from the kernel's object file tool (`objtool`), they are generally harmless. You can file an issue on the main issue tracker (https://github.com/ClangBuiltLinux/linux) but for me personally, `objtool` warnings are low priority because they are not always simple to fix.
