### ISSUE TITLE
BOLT's stage system requirements

### ISSUE THREAD

**Issue by commonuserlol** [ClangBuiltLinux/tc-build#268]
Hey, tysm for your work. I have a question, how much memory I need for BOLT? Exact value or just recommended. On machine with 14 cores and 11G ram (ubuntu VM) final stage with BOLT was killed by oom killer.

**Comment by nathanchance** [comment]
I am not sure, I do not usually do PGO+BOLT unless I have at least two times my number of threads for RAM. Are you building with LTO at all?

**Comment by commonuserlol** [comment]
Yes. The optimizations are ThinLTO, PGO, BOLT (projects are compiler-rt, clang, lld, polly, bolt, openmp)

**Comment by nathanchance** [comment]
Yeah, LTO (even thin) can consume quite a bit of memory, so you would be better off dropping it (it really does not improve performance for LLVM [in my experience](https://github.com/ClangBuiltLinux/cbl-meetup-2023/blob/main/nathan_making_llvm_faster_with_build_time_optimization_technologies.pdf) as much as you would think) or using `--defines` to set a lower value for [`LLVM_PARALLEL_LINK_JOBS`](https://llvm.org/docs/CMake.html#frequently-used-llvm-related-variables) [like I did](https://github.com/nathanchance/env/blob/132a01fb99f5331298a44e4711841bae739fb1cc/fish/functions/cbl_qualify_tc_bld_uprev.fish#L75).

**Comment by commonuserlol** [comment]
Actually I need fast as possible toolchain (cuz it will be used on device which have poor hardware specs). Is there recommended value of mem for ThinLTO + PGO + BOLT? Like 16 or 32G. I can do zram thing aswell.
Decrease parallel jobs will take longer time: ~4h with -j14 for PGO + ThinLTO (mainly due long linux kernel compilation for profiles) and with less parallel jobs it will be even slower.

**Comment by ptr1337** [comment]
This happens when the profile is to big. Generally perf2bolt uses around trice the memory of the profile size.
So, might try to use instrumenting instead of perf2bolt.

**Comment by commonuserlol** [comment]
oof alright, I'll try play with zram and tell you later

**Comment by commonuserlol** [comment]
The peak BOLT mem usage was ***17.5G***, most of time it was using ***~15G***. That means you need at least 18G of **free** RAM. Or zram trick as I did. But now I out of drive 💀. Profiles after BOLT used a lot of space.. Uh so, how much **drive space** needed for that?..

**Comment by nathanchance** [comment]
I cannot recall the necessary size to do BOLT but I would say anywhere from 100GB to 150GB is a good baseline for the source and build artifacts. I have seen instrumentation BOLT require 200GB or more.

Depending on your project requirements, you may be able to use the optimized toolchains that I provide on kernel.org to conserve your build resources: https://mirrors.edge.kernel.org/pub/tools/llvm/

**Comment by commonuserlol** [comment]
> from 100GB to 150GB

Alright I'll re-setup my VM for that.

> Depending on your project requirements, you may be able to use the optimized toolchains that I provide on kernel.org to conserve your build resources: https://mirrors.edge.kernel.org/pub/tools/llvm/

As I said before, I need fast as possible toolchain, also the size will be bigger with useless (for me) archs.

I think this can be closed, thanks a lot!
