### ISSUE TITLE
It seems like --targets option is broken

### ISSUE THREAD

**Issue by mxsleo** [ClangBuiltLinux/tc-build#273]
**Describe the bug**
Currently I am not absolutely sure the problem is with tc-build. But I tried several times and found out the following very stable pattern:
- Toolchain is built with ```--targets AArch64 ARM``` flag. Android kernel cross-compilation with ```LLVM=1``` option ends in the following:
```bash
error: 'No available targets are compatible with triple "x86_64-pc-linux-gnu"'
```
- Toolchain is built with default targets (when --targets flag is unset, which means ```all```). Android kernel compilation works at least to the menuconfig section with literally the same options.

**To Reproduce**
1. Clone https://github.com/Exynos64/android_kernel_eureka_exynos7885/tree/r15-buildsh with or without submodules (this will not affect the bug appearance, but saving disk space will not allow to test the full building possibility, which is, to be honest, is not needed and may fail due to the kernel source itself)
2. Build tc-build with ```--targets AArch64 ARM --use-good-revision``` flags and install it into the toolchain folder of the kernel (alternatively, you can use the incomplete builder script attached as a zipfile - just unpack it so that the build_kernel.sh part is inside the kernel root directory; take a look into lines **218** - which produces the wrong toolchain - and **219**, which makes the working one)
3. Try to build the kernel or at least the config with, for example, the following command:
```bash
PATH="$(pwd)/toolchain/bin:${PATH}" \
KBUILD_BUILD_USER="user" \
KBUILD_BUILD_HOST="pc" \
make \
    -j"$(nproc --all)" \
    LD_LIBRARY_PATH="$(pwd)/toolchain/lib:${LD_LIBRARY_PATH}" \
    LLVM=1 \
    CC=clang \
    AS=llvm-as LLVM_DIS=llvm-dis \
    LD=ld.lld NM=llvm-nm \
    OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump \
    STRIP=llvm-strip AR=llvm-ar \
    CLANG_TRIPLE=aarch64-linux-gnu- \
    CROSS_COMPILE=aarch64-linux-gnu- \
    CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
    ARCH=arm64 \
    ANDROID_MAJOR_VERSION=r \
    O=out \
    exynos7885-a40_defconfig
```
Actually, most of the variables are set by the Makefile, but I had not investigate seriously into that yet. The error happens even if shorten the command to ```PATH="$(pwd)/toolchain/bin:${PATH}" make ARCH=arm64 LLVM=1 exynos7885-a40_defconfig```.

**Expected behavior**
Building _aarch64-linux-gnu_ and _arm-linux-gnueabi_ targets when ```--targets AArch64 ARM``` flag is passed to the build script and not only when this option is unset and all of the targets are chosen.

**Screenshots**
![Screenshot_20240717_210313](https://github.com/user-attachments/assets/d7ef55d4-c315-4cc3-8afd-82a1ebee6c0a)
[kernel_root.zip](https://github.com/user-attachments/files/16272939/kernel_root.zip)

**Environment (please complete the following information):**
- Command you ran: [e.g. `./build-llvm.py`]:
```bash
build-llvm.py --install-folder="${_DEFTOOL}" --targets AArch64 ARM --use-good-revision
```
More in the "steps reproduction" section or in the script attached as a zip file.
- Distribution: [e.g. Debian stretch or Arch Linux]:
Debian GNU/Linux trixie/sid x86_64 (6.9.12-2-liquorix-amd64) - updated right a few hours ago
- Python version: [e.g. 3.7.3]
Python 3.12.4
- Shell: [e.g. zsh]
zsh 5.9 (x86_64-debian-linux-gnu)/GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)

**Comment by nathanchance** [comment]
You asked for only ARM targets but `LLVM=1` sets `HOSTCC` to `clang` and you are obviously building on an `x86_64`, so you should add `X86` to your list of targets.

**Comment by somestupidgirl** [comment]
I'm running into this exact same issue even with X86 target set:

./build-llvm.py --install-folder /path/to/folder --targets AArch64 ARM X86 --use-good-revision

Clang version:

$ clang --version
ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project 2ab9233f4f393c240c37ef092de09d907fe5c890)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /home/user/Android/Toolchains/clang/bin

Build log:

$ ./buildN9.sh
'/home/user/Android/exynos-linux-stable/arch/arm64/configs/exynos9810_defconfig' -> '/home/user/Android/exynos-linux-stable/arch/arm64/configs/exynos9810_temp_defconfig'
  HOSTCC  scripts/basic/fixdep
error: unable to create target: 'No available targets are compatible with triple "x86_64-pc-linux-gnu"'
1 error generated.
make[1]: *** [scripts/Makefile.host:101: scripts/basic/fixdep] Error 1
make: *** [Makefile:479: scripts_basic] Error 2
  HOSTCC  scripts/basic/fixdep
error: unable to create target: 'No available targets are compatible with triple "x86_64-pc-linux-gnu"'
1 error generated.
make[2]: *** [scripts/Makefile.host:101: scripts/basic/fixdep] Error 1
make[1]: *** [Makefile:479: scripts_basic] Error 2
make: *** No rule to make target 'include/config/auto.conf', needed by 'include/config/kernel.release'.  Stop.
Kernelcp: cannot stat '/home/user/Android/exynos-linux-stable/arch/arm64/boot/Image': No such file or directory
cp: cannot stat '/home/user/Android/exynos-linux-stable/arch/arm64/boot/dtb.img': No such file or directory

Kernel: https://github.com/somestupidgirl/exynos-linux-stable/tree/nh

**Comment by nathanchance** [comment]
Does

```
echo 'int main(void) { return 0; }' | /home/user/Android/Toolchains/clang/bin/clang -c -o /dev/null -x c -
```

work? If so, it means your path is messed up and that version of clang is not being used. If not, something else is up.

**Comment by somestupidgirl** [comment]
I figured out the issue. It was not path-related. It was a ccache issue. After clearing ccache I recompiled the toolchain and it's working as it should now. Thanks though. :)
