### ISSUE TITLE
Trying to build and full toolchain  based on 19.x

### ISSUE THREAD

**Issue by quic-seaswara** [ClangBuiltLinux/tc-build#278]
I am on version Ubuntu 18.04 and trying to use this repository to build a complete toolchain so that I can use the latest LLVM tools for my development needs.

I use this currently in this way below :-

 python3.9 build-llvm.py -f -r release/19.x  -D LLVM_ENABLE_RUNTIMES:STRING="libunwind;libcxxabi;libcxx" LLVM_CCACHE_BUILD:BOOL=ON LLVM_TOOL_MLIR_BUILD:BOOL=OFF LLVM_ALL_PROJECTS:STRING="bolt;clang;clang-tools-extra;compiler-rt;cross-project-tests;lld;lldb;pstl" -i  <install_path>

the bootstrap build is successful, but the final build fails with errors on libc/mlir/bolt.

Even if I have not enabled libc/mlir the final stage build builds all of them.

How do you use the scripts to build the full toolchain ? 

Thanks for all this work

**Comment by nathanchance** [comment]
I don't know if it is related but I don't think the `:<type>` part of the current `-D` value format of `<var_name>:<type>=<val>` is strictly necessary. Could you try your same command with the `-D` values formatted as `<var_name>=<val>` and see if that fixes it?

**Comment by quic-seaswara** [comment]
Thank you @nathanchance. I was able to finally build using this command line 

` python3.9 build-llvm.py -f -r release/19.x  -D  LLVM_ENABLE_RUNTIMES:STRING="libunwind;libcxxabi;libcxx" LLVM_CCACHE_BUILD=ON LLVM_TOOL_MLIR_BUILD=OFF MLIR_INCLUDE_TESTS=OFF  LLVM_ENABLE_PROJECTS:STRING="bolt;clang;mlir;clang-tools-extra;compiler-rt;cross-project-tests;lld;lldb;pstl" -i /local/mnt/workspace/seaswara/tc_build/ --no-ccache`

**Comment by quic-seaswara** [comment]
You can close the issue, and thanks for the support.
