### ISSUE TITLE
Adding --use-good-revision

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/tc-build#30]
I'm opening this to get general feedback on the concept before I go through and implement the option.

There are times where the LLVM tree may be in a broken state (build error or runtime failure). Given that this script is more aimed at kernel developers wanting to try new LLVM/Clang features but having to bother with debugging/triaging unrelated LLVM/Clang issues, it might be nice to have an option like `--use-good-revision` that will automatically checkout a known good working revision of LLVM that builds and works properly for the kernel's sake. This revision should be as close to tip of tree as possible so that the user is always getting the latest fixes.

Ideally, this option won't have to be used that often. The only problem that I can potentially foresee is a user cloning the script, never updating the script, and always using this option but I don't necessarily see that as a bad thing. If they ever run into a problem that we fixed in a newer version, we can just tell them to update the script to get that new revision.

Before bumping the revision, the user should run the `kernel/build.sh` script to qualify the revision being tested, ideally with `--allyesconfig` if #29 gets accepted to get the most coverage. I envision this revision bump happening every week or so.

Let me know if there are any potential issues I am not seeing. I am totally fine with not implementing this if people feel it is not a good idea but I think it would be beneficial to users who just want something that works.

**Comment by dileks** [comment]
In general I appreciate such an option.

A well working llvm-toolchain is the base for compiling software.

With a default value (Git sha1sum) and be able to set one by myself.

Good?
Currently I am building with...

```
cd tc-build

/build-llvm.py -p "clang;lld" -t "X86" --stage1-only
```

Good means for me Clang and LLD working well.

**Comment by nathanchance** [comment]
> be able to set one by myself

Do note that you can currently do this via the `-b` flag.

**Comment by dileks** [comment]
Hmm, as I see `release_90` Git branch was pushed.

```
./build-llvm.py -p "clang;lld" -t "X86" --stage1-only -b release_90
```

How do I combine a specific Git branch with a specific hash?

[1] https://lists.llvm.org/pipermail/llvm-branch-commits/2019-July/date.html

**Comment by MSF-Jarvis** [comment]
> Hmm, as I see `release_90` Git branch was pushed.
> 
> ```
> ./build-llvm.py -p "clang;lld" -t "X86" --stage1-only -b release_90
> ```
> 
> How do I combine a specific Git branch with a specific hash?
> 
> [1] https://lists.llvm.org/pipermail/llvm-branch-commits/2019-July/date.html

Just passing the hash to `-b` should be enough.

**Comment by dileks** [comment]
Do you mean...?

```
... -b release/9.x -b GIT_HASH
```

**Comment by MSF-Jarvis** [comment]
> Do you mean...?
> 
> ```
> ... -b release/9.x -b GIT_HASH
> ```

Just `-b GIT_HASH`

**Comment by dileks** [comment]
From my workflow I jump on the desired `GIT_BRANCH` and do if needed a `git reset {--hard} GIT_HASH`.

[1] https://github.com/llvm/llvm-project/commits/release/9.x
[2] https://github.com/llvm/llvm-project/commit/2cf681a11aea

**Comment by MSF-Jarvis** [comment]
> From my workflow I jump on the desired `GIT_BRANCH` and do if needed a `git reset {--hard} GIT_HASH`.
> 
> [1] https://github.com/llvm/llvm-project/commits/release/9.x
> [2] [llvm/llvm-project@2cf681a](https://github.com/llvm/llvm-project/commit/2cf681a11aea)

I suppose we can whip something up to support it. I found a problem with the checkout process which is tentatively fixed [here](https://github.com/MSF-Jarvis/tc-build/commits/msf/fetch-before-checkout) so I'd love to land that first before I triage this particular usecase.

**Comment by nathanchance** [comment]
@dileks I think implementing that will be rather convoluted (we’d have to add another parameter or some heuristic to giving both a branch and a hash). If you want to manually manage the repository like that, you should just pass `--no-pull` to the script (maybe should rename the option). I’d also argue that is an antipattern, you should ideally be using and testing the latest version of the software.
