### ISSUE TITLE
Ability to include tests for targets into build-dir

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#42]
Hi,

while digging into CBL issue #619 I would like to have tests for clang and lld targets.

This is adapted from a previous version of my script.

```
[ run_tests-lld.sh ]

#!/bin/sh
  
export LANG=C
export LC_ALL=C

BUILD_DIR="$(pwd)/build/stage1"

LLD_TESTS="ELF/x86-64-retpoline-linkerscript.s ELF/x86-64-retpoline-znow-linkerscript.s ELF/x86-64-retpoline-znow.s ELF/x86-64-retpoline.s"

LLVM_LIT_OPTS="--verbose --echo-all-commands --show-all"

cd $BUILD_DIR

for t in $LLD_TESTS ; do ./bin/llvm-lit $LLVM_LIT_OPTS ./lld/test/$t ; done
```

I was not able to include the $LLD_TESTS from `/path/to/tc-build/...` to run this.

**Comment by nathanchance** [comment]
Currently, this is hidden behind the `--debug` flag. However, I think it is worth breaking that flag up into `--build-type` (Debug, Release, RelWithDebInfo, etc), `--tests` (to build the tests), and `--assertions` (#40).
