### ISSUE TITLE
When BRANCH is a tag --incremental does not work

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#43]
Here we go:
```
$ ./scripts/build_tc-build.sh
projects...... clang;lld
targets....... X86
branch........ llvmorg-9.0.0-rc1
stage1-opts... --build-stage1-only --install-stage1-only
misc-opts..... --incremental
build-dir..... /home/sdi/src/llvm-toolchain/build
install-dir... /home/sdi/src/llvm-toolchain/install

========================
== Checking CC and LD ==
========================

CC: /usr/lib/llvm-9/bin/clang
CXX: /usr/lib/llvm-9/bin/clang++
LD: /usr/bin/ld.lld-9

===========================
== Checking dependencies ==
===========================

/usr/bin/cmake
/usr/bin/curl
/usr/bin/git
/usr/bin/ninja

===================
== Updating LLVM ==
===================

Note: checking out 'llvmorg-9.0.0-rc1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 6aa75a25bdee Merging r367215: ------------------------------------------------------------------------ r367215 | hans | 2019-07-29 11:49:04 +0200 (Mon, 29 Jul 2019) | 66 lines
```

```
$ cd tc-build/llvm-project
$ git branch
* (HEAD detached at llvmorg-9.0.0-rc1)
  release/9.x
```

UPDATE: Add correct log in Updating LLVM section

**Comment by nathanchance** [comment]
Does not work how? What do you expect it to do?

**Comment by dileks** [comment]
I checkout `release/9.x` Git branch and then tried a week later to checkout `llvmorg-9.0.0-rc1` Git tag by doing an incremental pull-ing.
Unsure if this is smart/allowed/foreseen-in-the-design.

Are remote Git tags fetched when using `-B/--branch` option?

**Comment by nathanchance** [comment]
Yes, we run `git fetch origin` which will fetch both new tags and branches. It looks like your example properly checked out. `llvmorg-9.0.0-rc1`?

**Comment by dileks** [comment]
The Git tag was indeed recognized/fetched.
```
$ git branch
* (HEAD detached at llvmorg-9.0.0-rc1)
  release/9.x
```

Manually I did:
```
$ cd tc-build/llvm-project

$ git ls-remote --tags origin | grep '9.0.0-rc1'
f85f31d608a7248e2fd419dee11371dcb9bd1efd        refs/tags/llvmorg-9.0.0-rc1
6aa75a25bdeea9cdc4b04cdd91e82e680444bf4b        refs/tags/llvmorg-9.0.0-rc1^{}

$ git checkout -b llvmorg-9.0.0-rc1 tags/llvmorg-9.0.0-rc1
```

In terms of a Git branch I expected to have exactly what the last line does: a local branch called `llvmorg-9.0.0-rc1` not `(HEAD detached at llvmorg-9.0.0-rc1)`.
Maybe this is just a cosmetical thing.

BTW, above I see two Git tags.
The commit-id `6aa75a25bdeea9cdc4b04cdd91e82e680444bf4b` is the commit-id of the `llvmorg-9.0.0-rc1` Git tag. What is the difference?

**Comment by nathanchance** [comment]
> In terms of a Git branch I expected to have exactly what the last line does: a local branch called `llvmorg-9.0.0-rc1` not `(HEAD detached at llvmorg-9.0.0-rc1)`.
> Maybe this is just a cosmetical thing.

The script runs `git checkout`, rather than `git checkout -b`. So by specifying `llvmorg-9.0.0-rc1` as the "branch", `git checkout` will put you into a detached HEAD state. If you want a branch instead, you should just manage the repository yourself and pass in `--no-update` to the script.

> BTW, above I see two Git tags.
> The commit-id `6aa75a25bdeea9cdc4b04cdd91e82e680444bf4b` is the commit-id of the `llvmorg-9.0.0-rc1` Git tag. What is the difference?

f85f31d608a7248e2fd419dee11371dcb9bd1efd is the tag object, 6aa75a25bdeea9cdc4b04cdd91e82e680444bf4b is the commit that the tag points to.
