### ISSUE TITLE
"--use-good-revision" don't work now

### ISSUE THREAD

**Issue by wloot** [ClangBuiltLinux/tc-build#57]
Traceback (most recent call last):
  File "./build-llvm.py", line 946, in <module>
    main()
  File "./build-llvm.py", line 939, in main
    fetch_llvm_binutils(root_folder, not args.no_update, ref)
  File "./build-llvm.py", line 442, in fetch_llvm_binutils
    check=True)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', '-b', '957b9cdd2692178b9635cbbbcb94e78a5bc24473', 'git://github.com/llvm/llvm-project', '<xxxxx>/llvm-project']' returned non-zero exit status 128.

also i ran the command locally and fails as well:
 git clone -b 957b9cdd2692178b9635cbbbcb94e78a5bc24473 git://github.com/llvm/llvm-project
Cloning into 'llvm-project'...
fatal: Remote branch 957b9cdd2692178b9635cbbbcb94e78a5bc24473 not found in upstream origin

I speculate that github has imposed restrictions on this.

more info:
https://stackoverflow.com/questions/3489173/how-to-clone-git-repository-with-specific-revision-changeset

**Comment by nathanchance** [comment]
This should be easy to solve by just closing the repo then running `git checkout`, which is probably a more supported way of doing things anyways. I will try to look at this tomorrow!

**Comment by ojeda** [comment]
`git clone` only claims to support a branch or tag name, not an arbitrary commit-ish, so I would think that is expected behavior.

**Comment by nathanchance** [comment]
That would make sense, I don't think I have ever tested `--use-good-revision` with a fresh checkout.
