### ISSUE TITLE
Host Freezes while Building LLVM stage 3 

### ISSUE THREAD

**Issue by chankruze** [ClangBuiltLinux/tc-build#59]
**Describe the bug**
Compilation hangs at Building LLVM stage 3. Job number 2257. It freezes the host PC/cloud instance. I tried on PC, it freezes and tried on could, the same happened.

**To Reproduce**
```
./build-llvm.py --lto=full --march=corei7 --pgo --targets=AArch64
```

**Expected behavior**
Expected it to pass and complete the build process.

**Screenshots**
![Stage 3](https://res.cloudinary.com/chankruze/image/upload/v1569773531/github/Screenshot_from_2019-09-29_21-39-57.png)

**Environment (please complete the following information):**
  - Command i ran: [`./build-llvm.py --lto=full --march=corei7 --pgo --targets=AArch64`]
  - Distribution: [Ubuntu 19.04]
  - Python version: [2.7.16 & 3.7.3]

**Comment by chankruze** [comment]
Is the `-m` requires what `uname -m` returns ?

```
chankruze@n00b-cloud:~/tc-build$ uname -m
x86_64
```

Should it be `x86_64` ? Anyway trying with this.

**Comment by nathanchance** [comment]
No, the `-m` is passed to `-march` so `x86_64` won’t work. 

I will take a look at this later today but can you do two things for me in the meantime?

1. Show me what `git -C llvm-project show` outputs.

2. Test either `--use-good-revision` or `--branch llvmorg-9.0.0` and see if it happens with one of those.

**Comment by chankruze** [comment]
I did a build without `-march`

```
./build-llvm.py --lto=full --pgo --targets=AArch64
```

This freezed at 
`[2264/3240] Building CXX object tools/clang/lib/AST/CMakeFiles/obj.clangAST.dir/CXXInheritance.cpp.o`

All above was based on master, i guess (default of the script). Now before your reply i already started building without any flag and with `--use-good-revision`.

**Your Task**
1. will do this as soon as current build finish. Currently it shows https://del.dog/lokayowilo.
2. Will do that also with the flags as soon as this finishes

**Comment by nathanchance** [comment]
I just ran the script with your same arguments (`./build-llvm.py --lto=full --march=corei7 --pgo --targets=AArch64`) and it compiled for me just fine at the below LLVM revision.

```
> git -C llvm-project show -s
commit a6d9d31279c83a25d4e4e44047d1349d1aac8d79 (HEAD -> master, origin/master, origin/HEAD)
Author: Aditya Kumar <hiraditya@msn.com>
Date:   Sun Sep 29 16:06:22 2019 +0000

    [LLVM-C][Ocaml] Add MergeFunctions and DCE pass
    
    MergeFunctions and DCE pass are missing from OCaml/C-api. This patch
    adds them.
    
    Differential Revision: https://reviews.llvm.org/D65071
    
    Reviewers: whitequark, hiraditya, deadalnix
    
    Reviewed By: whitequark
    
    Subscribers: llvm-commits
    
    Tags: #llvm
    
    Authored by: kren1
    
    llvm-svn: 373170
```

How much memory does your local machine and cloud instance have? LTO is a memory intensive task so you might see if it doesn't freeze without that.

**Comment by chankruze** [comment]
I have 8GB in both local & cloud.

**Comment by msfjarvis** [comment]
> I have 8GB RAM in both local & cloud. Yeh i tried with tht latest commit.
> 
> I think if RAM is an issue, then with or without flags it's not going to build on my machines.

You have enough memory for a normal build. LTO has elevated requirements for memory and processing power which is why your systems are freezing. Try building with no LTO and there's little chance you'll see identical behaviour.

**Comment by chankruze** [comment]
I am cretaing an instance with more memory, 16 GB. Hope it won't freeze.

**Comment by nathanchance** [comment]
If `--lto=full` continues to freeze, you might try `--lto=thin`, which is supposed to use significantly less memory (see [this blog post](http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html)). When I use `--lto=full`, my memory usage can spike above 60GB.

For the record, `--pgo` gives the single biggest run time improvement between the various optimization options that the script provides (`--lto=full`, `--lto=thin`, and `--pgo`), while having the fastest relative build time: https://gist.github.com/nathanchance/559c3e790972b56ffe674192a5f6d118

**Comment by nathanchance** [comment]
I am closing this as I don't believe it has anything to do with the script or LLVM. Please reopen if you can provide more information that proves otherwise. Thank you for using the script and giving feedback!
