### ISSUE TITLE
Compile fails on Manjaro

### ISSUE THREAD

**Issue by kristofpetho** [ClangBuiltLinux/tc-build#64]
**Describe the bug**
Stage 2 exits with an error

**To Reproduce**
clone tc-build, and run build-llvm.py

**Expected behavior**
it should compile cleanly

**Screenshots**
[26/4067] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CodeGenCoverage.cpp.o
FAILED: lib/Support/CMakeFiles/LLVMSupport.dir/CodeGenCoverage.cpp.o 
/home/kristof/android/tc-build/build/llvm/stage1/bin/clang++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/Support -I/home/kristof/android/tc-build/llvm-project/llvm/lib/Support -I/usr/include/libxml2 -Iinclude -I/home/kristof/android/tc-build/llvm-project/llvm/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG   -std=c++14  -fno-exceptions -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/CodeGenCoverage.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/CodeGenCoverage.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/CodeGenCoverage.cpp.o -c /home/kristof/android/tc-build/llvm-project/llvm/lib/Support/CodeGenCoverage.cpp
fatal error: error in backend: Cannot emit physreg copy instruction
[31/4067] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CommandLine.cpp.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "./build-llvm.py", line 890, in <module>
    main()
  File "./build-llvm.py", line 886, in main
    do_multistage_build(args, dirs, env_vars)
  File "./build-llvm.py", line 858, in do_multistage_build
    invoke_ninja(args, dirs, stage)
  File "./build-llvm.py", line 793, in invoke_ninja
    subprocess.run('ninja', check=True, cwd=build_folder)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ninja' returned non-zero exit status 1.

**Environment (please complete the following information):**
  - Command you ran: `./build-llvm.py`
  - Distribution: Manjaro Linux latest
  - Python version: 3.8.1

**Comment by msfjarvis** [comment]
Can you tell me the commit hash of the `llvm-project` repo in your tc-build directory? This appears to be a (hopefully temporary) regression in the LLVM tree but I'd like to confirm on a set of my machines as well.

**Comment by kristofpetho** [comment]
1132f87fbf1373835d7030354f6210c5dab62c3e

Thank you!

**Comment by msfjarvis** [comment]
> 1132f87fbf1373835d7030354f6210c5dab62c3e
> 

I had to step out for a bit, but builds were running in the mean time. `--stage-1-only` builds fine on this, and the standard build fails with the same issue you saw. I just moved to ToT at https://github.com/llvm/llvm-project/commit/92570718a86cc4c23108b596002114ab25857b14 and `--stage-1-only` builds fine once more. Will report back once the standard 2 stage build finishes on this.

**Comment by msfjarvis** [comment]
2 stage build works fine on https://github.com/llvm/llvm-project/commit/92570718a86cc4c23108b596002114ab25857b14 so I assume the regression was resolved upstream. @kristofpetho can you confirm on your end and close the issue?

**Comment by nathanchance** [comment]
The problematic commit was reverted: https://github.com/llvm/llvm-project/commit/d2b6ac6ccda5ad8e38eee38e7ee46acad03540be

I had this same issue and I can confirm that commit resolves it.

**Comment by kristofpetho** [comment]
Thank you both, I'm still building so wasn't able to confirm.
