### ISSUE TITLE
Allow shallow-clone to a specific branch or tag

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/tc-build#81]
I did a shallow-clone - but this clones Git master.
Switching to remote `release/10.x` is not possible out of this Git (or I did not find an appropriate solution).

Instructions:
```
cd tc-build

TC_OPTS=" --build-type Release -p clang;lld -t X86 -b release/10.x --shallow-clone --no-update --check-targets clang lld --build-stage1-only -B /home/dileks/src/llvm-toolchain/build --install-stage1-only -I /home/dileks/src/llvm-toolchain/install"

./build-llvm.py ${TC_OPTS}
```

A manual shallow-clone to a specific branch was succesful here (see [1], sorry partly German):
```
$ git clone --branch release/10.x --depth 1 git://github.com/llvm/llvm-project
Klone nach 'llvm-project' ...
remote: Enumerating objects: 94802, done.
remote: Counting objects: 100% (94802/94802), done.
remote: Compressing objects: 100% (83370/83370), done.
remote: Total 94802 (delta 15993), reused 53423 (delta 8081), pack-reused 0
Empfange Objekte: 100% (94802/94802), 127.46 MiB | 2.46 MiB/s, Fertig.
Löse Unterschiede auf: 100% (15993/15993), Fertig.
Aktualisiere Dateien: 100% (90213/90213), Fertig.

$ cd llvm-project/

$ git branch 
* release/10.x

$ git log --oneline -1
edbe962459da (grafted, HEAD -> release/10.x, origin/release/10.x) [COFF] Don't treat DWARF sections as GC roots
```

Desired is a working together of `--branch BRANCH` with `--shallow-clone` option.

[1] https://stackoverflow.com/questions/8932389/git-shallow-clone-to-specific-tag

**Comment by nathanchance** [comment]
So `--depth=1` in `git` implies `--single-branch` ([reference](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt)), which means that we only get the `master` branch since it is the default. We do not use the `--branch` parameter to `git clone` due to https://github.com/ClangBuiltLinux/tc-build/commit/925a80054c52f511ded181e992c99bcc436f77a4.

I can make your request work properly with the below diff but the caveat is that we are now fetching a shallow clone of all branches, which ultimately results in about `379.21 MiB` being fetched, versus `125.31 MiB` or so. It is up to you whether or not I push this, I do not use `--shallow-clone` and @kdrag0n only builds the master branch so this does not affect him. Otherwise, you can just continue to manage the repo manually if you care about the bandwidth savings.

```diff
diff --git a/build-llvm.py b/build-llvm.py
index a2e17e2..a3311fb 100755
--- a/build-llvm.py
+++ b/build-llvm.py
@@ -440,7 +440,11 @@ def fetch_llvm_binutils(root_folder, update, shallow, ref):
                                check=True,
                                cwd=cwd)
     else:
-        extra_args = ("--depth", "1") if shallow else ()
+        extra_args = ()
+        if shallow:
+            extra_args = ("--depth", "1")
+            if ref != "master":
+                extra_args += ("--no-single-branch",)
         utils.print_header("Downloading LLVM")
         subprocess.run([
             "git", "clone", *extra_args, **"git://github.com/llvm/llvm-project",**
```

**Comment by dileks** [comment]
What is the output of `git branch` and `git branch -r` with your diff?

I have archived today 2 tarballs with `master` and `release/10.x` Git branches of llvm-project shallow-cloned.
Means I have downloaded 2x 125MiB = 250MiB.
So 380MiB is OK for me vs. self-managed switching between these 2 tarballs.

**Comment by msfjarvis** [comment]
```
llvm-project (release/10.x) $ git branch
  master
* release/10.x
llvm-project (release/10.x) $ git branch -r
  origin/HEAD -> origin/master
  origin/master
  origin/release/1.0.x
  origin/release/1.1.x
  origin/release/1.2.x
  origin/release/1.3.x
  origin/release/1.4.x
  origin/release/1.5.x
  origin/release/1.6.x
  origin/release/1.7.x
  origin/release/1.8.x
  origin/release/1.9.x
  origin/release/10.x
  origin/release/2.0.x
  origin/release/2.1.x
  origin/release/2.2.x
  origin/release/2.3.x
  origin/release/2.4.x
  origin/release/2.5.x
  origin/release/2.6.x
  origin/release/2.7.x
  origin/release/2.8.x
  origin/release/2.9.x
  origin/release/3.0.x
  origin/release/3.1.x
  origin/release/3.2.x
  origin/release/3.3.x
  origin/release/3.4.x
  origin/release/3.5.x
  origin/release/3.6.x
  origin/release/3.7.x
  origin/release/3.8.x
  origin/release/3.9.x
  origin/release/4.x
  origin/release/5.x
  origin/release/6.x
  origin/release/7.x
  origin/release/8.x
  origin/release/9.x

```

This is the state of the repository after Nathan's diff was applied to a fresh clone of tc-build, and build-llvm.py invoked with `./build-llvm.py -s -b release/10.x`.

**Comment by dileks** [comment]
Cool :-).

Can you confirm the number of 380MiB data-usage from @nathanchance?

Many many thanks to both of you!

**Comment by msfjarvis** [comment]
> Cool :-).
> 
> Can you confirm the number of 380MiB data-usage from @nathanchance?
> 
> Many many thanks to both of you!

My `.git` folder is `400.1MB` so I guess his estimate is mostly accurate.

**Comment by dileks** [comment]
@nathanchance 

Can you push this, please?
Thanks.

**Comment by nathanchance** [comment]
I will push it once I have a version I am happy with.
