### ISSUE TITLE
Linking CXX shared module lib/LLVMgold.so FAILED

### ISSUE THREAD

**Issue by mcdachpappe** [ClangBuiltLinux/tc-build#85]
**Describe the bug**
build-llvm.py fails at step 3 of 3 as described below. However, using **--lto thin** works as intended but **--lto full** fails.

**To Reproduce**
1. build-llvm.py \
	--targets "ARM;AArch64;X86" \
	--use-good-revision \
	--pgo \
	--lto full

2. Script fails at stage 3 of 3:
`[3405/4091] Linking CXX shared module lib/LLVMgold.so
FAILED: lib/LLVMgold.so 
: && /home/danny/android/build-tools-llvm/build/llvm/stage1/bin/clang++ -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -w -fdiagnostics-color -ffunction-sections -fdata-sections -fprofile-instr-use="/home/danny/android/build-tools-llvm/build/llvm/profdata.prof" -flto=full -O3 -DNDEBUG  -Wl,-z,nodelete -fuse-ld=/home/danny/android/build-tools-llvm/build/llvm/stage1/bin/ld.lld -Wl,--color-diagnostics   -Wl,-O3 -Wl,--gc-sections  -Wl,--version-script,"/home/danny/android/build-tools-llvm/build/llvm/stage3/tools/gold/LLVMgold.exports" -shared  -o lib/LLVMgold.so tools/gold/CMakeFiles/LLVMgold.dir/gold-plugin.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib" lib/libLLVMARMCodeGen.a lib/libLLVMARMAsmParser.a lib/libLLVMARMDesc.a lib/libLLVMARMDisassembler.a lib/libLLVMARMInfo.a lib/libLLVMARMUtils.a lib/libLLVMAArch64CodeGen.a lib/libLLVMAArch64AsmParser.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Disassembler.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Utils.a lib/libLLVMX86CodeGen.a lib/libLLVMX86AsmParser.a lib/libLLVMX86Desc.a lib/libLLVMX86Disassembler.a lib/libLLVMX86Info.a lib/libLLVMX86Utils.a lib/libLLVMLinker.a lib/libLLVMLTO.a lib/libLLVMBitWriter.a lib/libLLVMipo.a lib/libLLVMARMDesc.a lib/libLLVMARMInfo.a lib/libLLVMARMUtils.a lib/libLLVMAArch64Desc.a lib/libLLVMAArch64Info.a lib/libLLVMAArch64Utils.a lib/libLLVMAsmPrinter.a lib/libLLVMDebugInfoDWARF.a lib/libLLVMCFGuard.a lib/libLLVMGlobalISel.a lib/libLLVMSelectionDAG.a lib/libLLVMMCDisassembler.a lib/libLLVMObjCARCOpts.a lib/libLLVMPasses.a lib/libLLVMCodeGen.a lib/libLLVMTarget.a lib/libLLVMCoroutines.a lib/libLLVMipo.a lib/libLLVMLinker.a lib/libLLVMBitWriter.a lib/libLLVMFrontendOpenMP.a lib/libLLVMIRReader.a lib/libLLVMAsmParser.a lib/libLLVMInstrumentation.a lib/libLLVMVectorize.a lib/libLLVMScalarOpts.a lib/libLLVMAggressiveInstCombine.a lib/libLLVMInstCombine.a lib/libLLVMTransformUtils.a lib/libLLVMAnalysis.a lib/libLLVMProfileData.a lib/libLLVMObject.a lib/libLLVMMCParser.a lib/libLLVMMC.a lib/libLLVMDebugInfoCodeView.a lib/libLLVMDebugInfoMSF.a lib/libLLVMBitReader.a lib/libLLVMTextAPI.a lib/libLLVMCore.a lib/libLLVMBinaryFormat.a lib/libLLVMRemarks.a lib/libLLVMBitstreamReader.a lib/libLLVMSupport.a -lz -lrt -ldl -lpthread -lm lib/libLLVMDemangle.a && :
clang-11: error: unable to execute command: Killed`

**Expected behavior**
Script should build and install toolchain correctly.

**Environment (please complete the following information):**
  - Command you ran: see step 1
  - Distribution: Ubuntu 18.04 [amd64]
  - Python version: 2.7.17

**Comment by nathanchance** [comment]
How much memory do you have?

**Comment by mcdachpappe** [comment]
> How much memory do you have?

I'm running Ubuntu in my virtual machine .. I assigned 13768 MB of RAM to it. My host system has 16GB of RAM

**Comment by nathanchance** [comment]
That won't be enough to use full LTO, [this server](https://www.packet.com/cloud/servers/c3-small/) was not able to do it. I believe that 64GB is pretty much the minimum that is needed for LLVM.

I'll add a note to the help text about this though since you are not the first person to bring this up (#59) and you probably won't be the last :)

For what it's worth, according to [my most recent LLVM benchmark](https://gist.github.com/nathanchance/976cb6f7bc5b630e7dd15b539d4e8040), I saw virtually no difference in compile times between an LLVM toolchain compiled with LTO versus Thin LTO but Thin LTO did take 15 minutes less on [a pretty beefy machine](https://www.packet.com/cloud/servers/g2-large/).

Thank you for using the script and giving me feedback, it means a lot!

**Comment by mcdachpappe** [comment]
Thank you for your efforts!
